// Code generated by Valgo; DO NOT EDIT.

package valgo

type ValidatorComplex64 struct {
	context *ValidatorContext
}

func Complex64(value complex64, nameAndTitle ...string) *ValidatorComplex64 {
	return &ValidatorComplex64{context: NewContext(value, nameAndTitle...)}
}

func (validator *ValidatorComplex64) Context() *ValidatorContext {
	return validator.context
}

func (validator *ValidatorComplex64) EqualTo(value complex64, template ...string) *ValidatorComplex64 {
	validator.context.AddWithValue(
		func() bool {
			return validator.context.Value().(complex64) == value
		},
		ErrorKeyEqualTo, value, template...)

	return validator
}

func (validator *ValidatorComplex64) Zero(value complex64, template ...string) *ValidatorComplex64 {
	validator.context.AddWithValue(
		func() bool {
			return validator.context.Value().(complex64) == 0
		},
		ErrorKeyZero, value, template...)

	return validator
}

func (validator *ValidatorComplex64) Passing(function func(v complex64) bool, template ...string) *ValidatorComplex64 {
	validator.context.Add(
		func() bool {
			return function(validator.context.Value().(complex64))
		},
		ErrorKeyPassing, template...)

	return validator
}

func (validator *ValidatorComplex64) InSlice(slice []complex64, template ...string) *ValidatorComplex64 {
	validator.context.AddWithValue(
		func() bool {
			for _, v := range slice {
				if validator.context.Value() == v {
					return true
				}
			}
			return false
		},
		ErrorKeyInSlice, validator.context.Value(), template...)

	return validator
}

func (validator *ValidatorComplex64) Not() *ValidatorComplex64 {
	validator.context.Not()

	return validator
}
