// Code generated by Valgo; DO NOT EDIT.

package valgo

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestComplex128EqualToValid(t *testing.T) {
	ResetMessages()

	v := Is(Complex128(complex128(10)).EqualTo(complex128(10)))
	assert.True(t, v.Valid())
	assert.Empty(t, v.Errors())

	v = Is(Complex128(complex128(1)).EqualTo(complex128(10)))
	assert.False(t, v.Valid())
	assert.Len(t, v.Errors(), 1)
}
