on:
  push:
    branches:
      - master
      - main
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"

name: Tests
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x, 1.22.x]
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Fetch Git Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.11.0

      - name: Run Tests
        run: gotestsum -f testname -- ./... -race -count=1
