on:
  push:
    branches:
      - master
      - main
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"

name: Tests
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x, 1.24.x, 1.25.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Fetch Git Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        env:
          GOTOOLCHAIN: auto
        run: go install gotest.tools/gotestsum@latest

      - name: Run Tests
        run: gotestsum -f testname -- ./... -race -count=1
